import type { Page } from 'patchright'

import type { CustomRunner } from '../../../types/adapter.js'
/**
 * Xiaohongshu (小红书) L3 adapter — Vue SSR state extraction + comment API interception.
 *
 * XHS is a Vue 3 SSR app. All data lives in window.__INITIAL_STATE__ after page load.
 * Direct API calls fail (500) because XHS requires anti-bot signature headers (X-s, X-t, X-s-common)
 * generated by obfuscated JS. Instead we navigate to the right page and read Vue SSR state.
 *
 * Comments are loaded async by the page's own JS — we intercept the API response.
 */

type Errors = { missingParam(name: string): Error; unknownOp(op: string): Error; needsLogin(): Error; wrap(error: unknown): Error }

/** Deeply-nested SSR state node — self-referential index signature replaces `any` for Vue reactive state. */
interface SsrNode { readonly [key: string]: SsrNode }

/** Window with XHS Vue SSR __INITIAL_STATE__ */
type XhsWindow = Window & typeof globalThis & { __INITIAL_STATE__?: SsrNode }

const BASE = 'https://www.xiaohongshu.com'

/* ---------- helpers ---------- */

function asRecord(val: unknown): Record<string, unknown> {
  return (val && typeof val === 'object' ? val : {}) as Record<string, unknown>
}

/* ---------- operation handlers ---------- */

async function searchNotes(page: Page, params: Record<string, unknown>, errors: Errors): Promise<unknown> {
  const keyword = String(params.keyword ?? params.query ?? '')
  if (!keyword) throw errors.missingParam('keyword')
  const searchApiPromise = page.waitForResponse(
    (resp) => resp.url().includes('/api/sns/web/v1/search/notes') && resp.status() === 200,
    { timeout: 15000 },
  ).catch(() => null)
  await page.goto(
    `${BASE}/search_result?keyword=${encodeURIComponent(keyword)}&source=web_search_result_notes`,
    { waitUntil: 'domcontentloaded', timeout: 30000 },
  )
  await page.waitForTimeout(4000)
  const needsLogin = await page.evaluate(() => document.body.innerText.includes('登录后查看搜索结果'))
  if (needsLogin) throw errors.needsLogin()
  const ssrResult = await page.evaluate(() => {
    const state = (window as XhsWindow).__INITIAL_STATE__
    if (!state?.search) return null
    const feedsRef = state.search.feeds
    const feeds: SsrNode[] = feedsRef?._rawValue ?? feedsRef ?? []
    if (!Array.isArray(feeds) || feeds.length === 0) return null
    const notes = feeds
      .filter((f: SsrNode) => f.modelType === 'note' && f.noteCard)
      .map((f: SsrNode) => {
        const card = f.noteCard
        return {
          noteId: f.id, xsecToken: f.xsecToken, type: card.type, displayTitle: card.displayTitle,
          user: card.user ? { userId: card.user.userId, nickname: card.user.nickname, avatar: card.user.avatar } : null,
          likedCount: card.interactInfo?.likedCount ?? null,
          cover: card.cover ? { url: card.cover.urlDefault, width: card.cover.width, height: card.cover.height } : null,
        }
      })
    return notes.length > 0 ? { notes, count: notes.length } : null
  })
  if (ssrResult) return ssrResult
  const searchResp = await searchApiPromise
  if (searchResp) {
    try {
      const json = (await searchResp.json()) as Record<string, unknown>
      const data = asRecord(json.data)
      const items = data.items as Array<Record<string, unknown>> | undefined
      if (Array.isArray(items) && items.length > 0) {
        const notes = items
          .filter((item: SsrNode) => item.model_type === 'note' && item.note_card)
          .map((item: SsrNode) => {
            const card = item.note_card
            return {
              noteId: item.id, xsecToken: item.xsec_token, type: card.type, displayTitle: card.display_title,
              user: card.user ? { userId: card.user.user_id, nickname: card.user.nickname, avatar: card.user.avatar } : null,
              likedCount: card.interact_info?.liked_count ?? null,
              cover: card.cover ? { url: card.cover.url_default ?? card.cover.url, width: card.cover.width, height: card.cover.height } : null,
            }
          })
        return { notes, count: notes.length }
      }
    } catch { /* intentional: API parse failed */ }
  }
  return { notes: [], count: 0 }
}

async function getNoteDetail(page: Page, params: Record<string, unknown>, errors: Errors): Promise<unknown> {
  const noteId = String(params.noteId ?? params.note_id ?? '')
  if (!noteId) throw errors.missingParam('noteId')
  const xsecToken = String(params.xsecToken ?? params.xsec_token ?? '')
  const commentPromise = page.waitForResponse(
    (resp) => resp.url().includes('/api/sns/web/v2/comment/page') && resp.status() === 200,
    { timeout: 15000 },
  ).catch(() => null)
  const tokenParam = xsecToken ? `&xsec_token=${encodeURIComponent(xsecToken)}` : ''
  await page.goto(`${BASE}/explore/${noteId}?xsec_source=pc_search${tokenParam}`, { waitUntil: 'domcontentloaded', timeout: 30000 })
  await page.waitForFunction(
    (id: string) => {
      const state = (window as XhsWindow).__INITIAL_STATE__
      if (!state?.note?.noteDetailMap) return false
      const map = state.note.noteDetailMap._rawValue ?? state.note.noteDetailMap
      return !!(map && typeof map === 'object' && map[id])
    }, noteId, { timeout: 10000 },
  ).catch(() => null)
  const noteData = await page.evaluate((id: string) => {
    const state = (window as XhsWindow).__INITIAL_STATE__
    if (!state?.note) return null
    const mapRef = state.note.noteDetailMap
    const map: Record<string, SsrNode> = mapRef?._rawValue ?? mapRef ?? {}
    const entry = map[id]
    if (!entry) return null
    const detail = entry.note ?? entry
    const rawTitle = detail.title || detail.displayTitle || ''
    const title = rawTitle || (detail.desc ? String(detail.desc).split(/[#\n]/)[0].trim().slice(0, 80) : '')
    return {
      noteId: detail.noteId, title, desc: detail.desc, type: detail.type,
      time: detail.time, lastUpdateTime: detail.lastUpdateTime,
      user: detail.user ? { userId: detail.user.userId, nickname: detail.user.nickname, avatar: detail.user.avatar } : null,
      interactInfo: detail.interactInfo ? {
        likedCount: detail.interactInfo.likedCount, collectedCount: detail.interactInfo.collectedCount,
        commentCount: detail.interactInfo.commentCount, shareCount: detail.interactInfo.shareCount,
      } : null,
      tagList: Array.isArray(detail.tagList) ? detail.tagList.map((t: SsrNode) => ({ id: t.id, name: t.name, type: t.type })) : [],
      imageCount: detail.imageList?.length ?? 0,
    }
  }, noteId)
  let comments: unknown[] = []
  const commentResp = await commentPromise
  if (commentResp) {
    try {
      const json = (await commentResp.json()) as Record<string, unknown>
      const data = asRecord(json.data)
      const rawComments = data.comments as Array<Record<string, unknown>> | undefined
      if (Array.isArray(rawComments)) {
        comments = rawComments.slice(0, 20).map((c) => ({
          id: c.id, content: c.content, likeCount: c.like_count, createTime: c.create_time,
          ipLocation: c.ip_location, subCommentCount: c.sub_comment_count,
          user: c.user_info ? {
            userId: (c.user_info as Record<string, unknown>).user_id,
            nickname: (c.user_info as Record<string, unknown>).nickname,
            avatar: (c.user_info as Record<string, unknown>).image,
          } : null,
        }))
      }
    } catch { /* intentional */ }
  }
  return { note: noteData, comments }
}

async function getUserProfile(page: Page, params: Record<string, unknown>, errors: Errors): Promise<unknown> {
  const userId = String(params.userId ?? params.user_id ?? '')
  if (!userId) throw errors.missingParam('userId')
  await page.goto(`${BASE}/user/profile/${userId}`, { waitUntil: 'domcontentloaded', timeout: 30000 })
  if (page.url().includes('login')) throw errors.needsLogin()
  if (page.url().includes('captcha')) throw errors.needsLogin()
  await page.waitForTimeout(4000)
  return page.evaluate(() => {
    const state = (window as XhsWindow).__INITIAL_STATE__
    if (!state?.user) return null
    const pageDataRef = state.user.userPageData
    const pageData: Record<string, SsrNode> = pageDataRef?._rawValue ?? pageDataRef ?? {}
    const basicInfo = pageData.basicInfo?._rawValue ?? pageData.basicInfo ?? {}
    const interactions = pageData.interactions?._rawValue ?? pageData.interactions ?? []
    const tags = pageData.tags?._rawValue ?? pageData.tags ?? []
    return {
      userId: basicInfo.redId ?? null, nickname: basicInfo.nickname ?? null, desc: basicInfo.desc ?? null,
      gender: basicInfo.gender ?? null, avatar: basicInfo.images ?? null, avatarLarge: basicInfo.imageb ?? null,
      ipLocation: basicInfo.ipLocation ?? null,
      interactions: Array.isArray(interactions) ? interactions.map((i: SsrNode) => ({ type: i.type, name: i.name, count: i.count })) : [],
      tags: Array.isArray(tags) ? tags.map((t: SsrNode) => ({ name: t.name, tagType: t.tagType })) : [],
    }
  })
}

async function getUserNotes(page: Page, params: Record<string, unknown>, errors: Errors): Promise<unknown> {
  const userId = String(params.userId ?? params.user_id ?? '')
  if (!userId) throw errors.missingParam('userId')
  await page.goto(`${BASE}/user/profile/${userId}`, { waitUntil: 'domcontentloaded', timeout: 30000 })
  if (page.url().includes('login')) throw errors.needsLogin()
  if (page.url().includes('captcha')) throw errors.needsLogin()
  await page.waitForTimeout(4000)
  return page.evaluate(() => {
    const state = (window as XhsWindow).__INITIAL_STATE__
    if (!state?.user) return { notes: [], count: 0 }
    const notesRef = state.user.notes
    const notePages: SsrNode[] = notesRef?._rawValue ?? notesRef ?? []
    if (!Array.isArray(notePages) || notePages.length === 0) return { notes: [], count: 0 }
    const allNotes: SsrNode[] = []
    for (const page of notePages) {
      const items: SsrNode[] = page?._rawValue ?? page ?? []
      if (Array.isArray(items)) {
        for (const item of items) {
          if (item?.noteCard) {
            const card = item.noteCard
            allNotes.push({
              noteId: item.id, xsecToken: item.xsecToken, type: card.type, displayTitle: card.displayTitle,
              user: card.user ? { userId: card.user.userId, nickname: card.user.nickname, avatar: card.user.avatar } : null,
              likedCount: card.interactInfo?.likedCount ?? null,
              cover: card.cover ? { url: card.cover.urlDefault, width: card.cover.width, height: card.cover.height } : null,
            })
          }
        }
      }
    }
    return { notes: allNotes, count: allNotes.length }
  })
}

async function getExploreFeed(page: Page, _params: Record<string, unknown>, _errors: Errors): Promise<unknown> {
  await page.goto(`${BASE}/explore`, { waitUntil: 'domcontentloaded', timeout: 30000 })
  await page.waitForTimeout(4000)
  return page.evaluate(() => {
    const state = (window as XhsWindow).__INITIAL_STATE__
    if (!state?.feed) return { notes: [], count: 0 }
    const feedsRef = state.feed.feeds
    const feeds: SsrNode[] = feedsRef?._rawValue ?? feedsRef ?? []
    if (!Array.isArray(feeds)) return { notes: [], count: 0 }
    const notes = feeds
      .filter((f: SsrNode) => f.modelType === 'note' && f.noteCard)
      .map((f: SsrNode) => {
        const card = f.noteCard
        return {
          noteId: f.id, xsecToken: f.xsecToken, type: card.type, displayTitle: card.displayTitle,
          user: card.user ? { userId: card.user.userId, nickname: card.user.nickname, avatar: card.user.avatar } : null,
          likedCount: card.interactInfo?.likedCount ?? null,
          cover: card.cover ? { url: card.cover.urlDefault, width: card.cover.width, height: card.cover.height } : null,
        }
      })
    return { notes, count: notes.length }
  })
}

async function navigateToNote(page: Page, params: Record<string, unknown>, errors: Errors): Promise<string> {
  const noteId = String(params.noteId ?? params.note_id ?? '')
  if (!noteId) throw errors.missingParam('noteId')
  const xsecToken = String(params.xsecToken ?? params.xsec_token ?? '')
  const tokenParam = xsecToken ? `&xsec_token=${encodeURIComponent(xsecToken)}` : ''
  await page.goto(`${BASE}/explore/${noteId}?xsec_source=pc_search${tokenParam}`, { waitUntil: 'domcontentloaded', timeout: 30000 })
  await page.waitForFunction(
    (id: string) => {
      const state = (window as XhsWindow).__INITIAL_STATE__
      if (!state?.note?.noteDetailMap) return false
      const map = state.note.noteDetailMap._rawValue ?? state.note.noteDetailMap
      return !!(map && typeof map === 'object' && map[id])
    }, noteId, { timeout: 10000 },
  ).catch(() => null)
  return noteId
}

async function likeNote(page: Page, params: Record<string, unknown>, errors: Errors): Promise<unknown> {
  const noteId = await navigateToNote(page, params, errors)
  const wasLiked = await page.evaluate(() => {
    const state = (window as XhsWindow).__INITIAL_STATE__
    const mapRef = state?.note?.noteDetailMap
    const map: Record<string, SsrNode> = mapRef?._rawValue ?? mapRef ?? {}
    const entry = Object.values(map)[0] as SsrNode
    return (entry?.note ?? entry)?.interactInfo?.liked ?? false
  })
  if (wasLiked) return { noteId, liked: true, action: 'already_liked' }
  const likePromise = page.waitForResponse(
    (resp) => resp.url().includes('/api/sns/web/v1/note/like') && resp.status() === 200,
    { timeout: 10000 },
  ).catch(() => null)
  await page.click('.engage-bar-style .like-wrapper', { timeout: 5000 })
  const likeResp = await likePromise
  const success = !!likeResp
  return { noteId, liked: success, action: success ? 'liked' : 'failed' }
}

async function bookmarkNote(page: Page, params: Record<string, unknown>, errors: Errors): Promise<unknown> {
  const noteId = await navigateToNote(page, params, errors)
  const wasCollected = await page.evaluate(() => {
    const state = (window as XhsWindow).__INITIAL_STATE__
    const mapRef = state?.note?.noteDetailMap
    const map: Record<string, SsrNode> = mapRef?._rawValue ?? mapRef ?? {}
    const entry = Object.values(map)[0] as SsrNode
    return (entry?.note ?? entry)?.interactInfo?.collected ?? false
  })
  if (wasCollected) return { noteId, bookmarked: true, action: 'already_bookmarked' }
  const collectPromise = page.waitForResponse(
    (resp) => resp.url().includes('/api/sns/web/v1/note/collect') && resp.status() === 200,
    { timeout: 10000 },
  ).catch(() => null)
  await page.click('.engage-bar-style .collect-wrapper', { timeout: 5000 })
  const collectResp = await collectPromise
  const success = !!collectResp
  return { noteId, bookmarked: success, action: success ? 'bookmarked' : 'failed' }
}

async function getHotSearch(page: Page, _params: Record<string, unknown>, _errors: Errors): Promise<unknown> {
  const trendingPromise = page.waitForResponse(
    (resp) => resp.url().includes('/api/sns/web/v1/search/querytrending') && resp.status() === 200,
    { timeout: 15000 },
  ).catch(() => null)
  await page.goto(`${BASE}/explore`, { waitUntil: 'domcontentloaded', timeout: 30000 })
  await page.waitForTimeout(2000)
  const searchInput = page.locator('#search-input, .search-input').first()
  await searchInput.click({ timeout: 5000 }).catch(() => null)
  await page.waitForTimeout(1000)
  const trendingResp = await trendingPromise
  if (trendingResp) {
    try {
      const json = (await trendingResp.json()) as Record<string, unknown>
      const data = asRecord(json.data)
      const candidates = [data.items, data.list, data.trendings]
      const firstArrayKey = Object.keys(data).find(k => Array.isArray(data[k]))
      if (firstArrayKey) candidates.push(data[firstArrayKey] as Array<Record<string, unknown>>)
      const rawItems = candidates.find(c => Array.isArray(c) && c.length > 0) as Array<Record<string, unknown>> | undefined
      if (rawItems) {
        const items = rawItems.map((h: SsrNode, i: number) => ({
          keyword: h.name ?? h.word ?? h.keyword ?? h.title ?? '', score: h.score ?? h.hot_value ?? null, rank: h.rank ?? i + 1,
        }))
        return { items: items.filter(it => it.keyword), count: items.filter(it => it.keyword).length }
      }
    } catch { /* fall through to SSR */ }
  }

  const ssrResult = await page.evaluate(() => {
    const state = (window as XhsWindow).__INITIAL_STATE__
    if (!state?.search) return null
    const trendingRef = state.search.trending ?? state.search.hotList ?? state.search.queryTrending
    const trends: SsrNode[] = trendingRef?._rawValue ?? trendingRef ?? []
    if (!Array.isArray(trends) || trends.length === 0) return null
    const items = trends.map((t: SsrNode, i: number) => ({
      keyword: t.name ?? t.word ?? t.keyword ?? t.title ?? '',
      score: t.score ?? t.hot_value ?? null,
      rank: t.rank ?? i + 1,
    }))
    return items.filter((it: { keyword: string }) => it.keyword).length > 0
      ? { items: items.filter((it: { keyword: string }) => it.keyword), count: items.filter((it: { keyword: string }) => it.keyword).length }
      : null
  })
  if (ssrResult) return ssrResult

  return { items: [], count: 0 }
}

async function getNoteComments(page: Page, params: Record<string, unknown>, errors: Errors): Promise<unknown> {
  const noteId = String(params.noteId ?? params.note_id ?? '')
  if (!noteId) throw errors.missingParam('noteId')
  const xsecToken = String(params.xsecToken ?? params.xsec_token ?? '')
  const commentPromise = page.waitForResponse(
    (resp) => resp.url().includes('/api/sns/web/v2/comment/page') && resp.status() === 200,
    { timeout: 15000 },
  ).catch(() => null)
  const tokenParam = xsecToken ? `&xsec_token=${encodeURIComponent(xsecToken)}` : ''
  await page.goto(`${BASE}/explore/${noteId}?xsec_source=pc_search${tokenParam}`, { waitUntil: 'domcontentloaded', timeout: 30000 })
  await page.waitForFunction(() => !!(window as XhsWindow).__INITIAL_STATE__?.note, { timeout: 10000 }).catch(() => null)
  const commentResp = await commentPromise
  if (!commentResp) return { comments: [], count: 0, hasMore: false }
  try {
    const json = (await commentResp.json()) as Record<string, unknown>
    const data = asRecord(json.data)
    const rawComments = data.comments as Array<Record<string, unknown>> | undefined
    const hasMore = Boolean(data.has_more)
    const cursor = String(data.cursor ?? '')
    const comments = Array.isArray(rawComments)
      ? rawComments.slice(0, 20).map((c) => ({
          id: c.id, content: c.content, likeCount: c.like_count, createTime: c.create_time,
          ipLocation: c.ip_location, subCommentCount: c.sub_comment_count,
          user: c.user_info ? {
            userId: (c.user_info as Record<string, unknown>).user_id,
            nickname: (c.user_info as Record<string, unknown>).nickname,
            avatar: (c.user_info as Record<string, unknown>).image,
          } : null,
        }))
      : []
    return { comments, count: comments.length, hasMore, cursor }
  } catch { return { comments: [], count: 0, hasMore: false } }
}

async function getUserCollections(page: Page, params: Record<string, unknown>, errors: Errors): Promise<unknown> {
  const userId = String(params.userId ?? params.user_id ?? '')
  if (!userId) throw errors.missingParam('userId')
  await page.goto(`${BASE}/user/profile/${userId}`, { waitUntil: 'domcontentloaded', timeout: 30000 })
  if (page.url().includes('login')) throw errors.needsLogin()
  if (page.url().includes('captcha')) throw errors.needsLogin()
  await page.waitForTimeout(3000)
  const collectApiPromise = page.waitForResponse(
    (resp) => resp.url().includes('/api/sns/web/v1/user/collect') && resp.status() === 200,
    { timeout: 10000 },
  ).catch(() => null)
  await page.click('[class*="tab"]:has-text("收藏")', { timeout: 5000 }).catch(() => null)
  await page.waitForTimeout(2000)
  const collectResp = await collectApiPromise
  if (collectResp) {
    try {
      const json = (await collectResp.json()) as Record<string, unknown>
      const data = asRecord(json.data)
      const rawNotes = data.notes as Array<Record<string, unknown>> | undefined
      if (Array.isArray(rawNotes) && rawNotes.length > 0) {
        const notes = rawNotes.map((item: SsrNode) => ({
          noteId: item.note_id ?? item.id, xsecToken: item.xsec_token ?? null,
          type: item.type, displayTitle: item.display_title ?? '',
          user: item.user ? { userId: item.user.user_id ?? item.user.userId, nickname: item.user.nickname, avatar: item.user.avatar } : null,
          likedCount: item.interact_info?.liked_count ?? item.liked_count ?? null,
          cover: item.cover ? { url: item.cover.url ?? item.cover.urlDefault, width: item.cover.width, height: item.cover.height } : null,
        }))
        return { notes, count: notes.length }
      }
    } catch { /* fall through to SSR */ }
  }
  return page.evaluate(() => {
    const state = (window as XhsWindow).__INITIAL_STATE__
    if (!state?.user) return { notes: [], count: 0 }
    const collectRef = state.user.collect
    const collectPages: SsrNode[] = collectRef?._rawValue ?? collectRef ?? []
    if (!Array.isArray(collectPages) || collectPages.length === 0) return { notes: [], count: 0 }
    const allNotes: SsrNode[] = []
    for (const pg of collectPages) {
      const items: SsrNode[] = pg?._rawValue ?? pg ?? []
      if (Array.isArray(items)) {
        for (const item of items) {
          if (item?.noteCard) {
            const card = item.noteCard
            allNotes.push({
              noteId: item.id, xsecToken: item.xsecToken, type: card.type, displayTitle: card.displayTitle,
              user: card.user ? { userId: card.user.userId, nickname: card.user.nickname, avatar: card.user.avatar } : null,
              likedCount: card.interactInfo?.likedCount ?? null,
              cover: card.cover ? { url: card.cover.urlDefault, width: card.cover.width, height: card.cover.height } : null,
            })
          }
        }
      }
    }
    return { notes: allNotes, count: allNotes.length }
  })
}

async function getUserLiked(page: Page, params: Record<string, unknown>, errors: Errors): Promise<unknown> {
  const userId = String(params.userId ?? params.user_id ?? '')
  if (!userId) throw errors.missingParam('userId')
  await page.goto(`${BASE}/user/profile/${userId}`, { waitUntil: 'domcontentloaded', timeout: 30000 })
  if (page.url().includes('login')) throw errors.needsLogin()
  if (page.url().includes('captcha')) throw errors.needsLogin()
  await page.waitForTimeout(3000)
  const likedApiPromise = page.waitForResponse(
    (resp) => resp.url().includes('/api/sns/web/v1/user/like') && resp.status() === 200,
    { timeout: 10000 },
  ).catch(() => null)
  await page.click('[class*="tab"]:has-text("赞过")', { timeout: 5000 }).catch(() => null)
  await page.waitForTimeout(2000)
  const likedResp = await likedApiPromise
  if (likedResp) {
    try {
      const json = (await likedResp.json()) as Record<string, unknown>
      const data = asRecord(json.data)
      const rawNotes = data.notes as Array<Record<string, unknown>> | undefined
      if (Array.isArray(rawNotes) && rawNotes.length > 0) {
        const notes = rawNotes.map((item: SsrNode) => ({
          noteId: item.note_id ?? item.id, xsecToken: item.xsec_token ?? null,
          type: item.type, displayTitle: item.display_title ?? '',
          user: item.user ? { userId: item.user.user_id ?? item.user.userId, nickname: item.user.nickname, avatar: item.user.avatar } : null,
          likedCount: item.interact_info?.liked_count ?? item.liked_count ?? null,
          cover: item.cover ? { url: item.cover.url ?? item.cover.urlDefault, width: item.cover.width, height: item.cover.height } : null,
        }))
        return { notes, count: notes.length }
      }
    } catch { /* fall through to SSR */ }
  }
  return page.evaluate(() => {
    const state = (window as XhsWindow).__INITIAL_STATE__
    if (!state?.user) return { notes: [], count: 0 }
    const likedRef = state.user.liked
    const likedPages: SsrNode[] = likedRef?._rawValue ?? likedRef ?? []
    if (!Array.isArray(likedPages) || likedPages.length === 0) return { notes: [], count: 0 }
    const allNotes: SsrNode[] = []
    for (const pg of likedPages) {
      const items: SsrNode[] = pg?._rawValue ?? pg ?? []
      if (Array.isArray(items)) {
        for (const item of items) {
          if (item?.noteCard) {
            const card = item.noteCard
            allNotes.push({
              noteId: item.id, xsecToken: item.xsecToken, type: card.type, displayTitle: card.displayTitle,
              user: card.user ? { userId: card.user.userId, nickname: card.user.nickname, avatar: card.user.avatar } : null,
              likedCount: card.interactInfo?.likedCount ?? null,
              cover: card.cover ? { url: card.cover.urlDefault, width: card.cover.width, height: card.cover.height } : null,
            })
          }
        }
      }
    }
    return { notes: allNotes, count: allNotes.length }
  })
}

async function getRelatedNotes(page: Page, params: Record<string, unknown>, errors: Errors): Promise<unknown> {
  const noteId = String(params.noteId ?? params.note_id ?? '')
  if (!noteId) throw errors.missingParam('noteId')
  const xsecToken = String(params.xsecToken ?? params.xsec_token ?? '')
  const tokenParam = xsecToken ? `&xsec_token=${encodeURIComponent(xsecToken)}` : ''
  await page.goto(`${BASE}/explore/${noteId}?xsec_source=pc_search${tokenParam}`, { waitUntil: 'domcontentloaded', timeout: 30000 })
  await page.waitForFunction(
    (id: string) => {
      const state = (window as XhsWindow).__INITIAL_STATE__
      if (!state?.note?.noteDetailMap) return false
      const map = state.note.noteDetailMap._rawValue ?? state.note.noteDetailMap
      return !!(map && typeof map === 'object' && map[id])
    }, noteId, { timeout: 10000 },
  ).catch(() => null)
  const tagKeyword = await page.evaluate((id: string) => {
    const state = (window as XhsWindow).__INITIAL_STATE__
    if (!state?.note) return null
    const mapRef = state.note.noteDetailMap
    const map: Record<string, SsrNode> = mapRef?._rawValue ?? mapRef ?? {}
    const entry = map[id]
    if (!entry) return null
    const detail = entry.note ?? entry
    const tags: SsrNode[] = detail.tagList ?? []
    if (Array.isArray(tags) && tags.length > 0) {
      const topicTag = tags.find((t: SsrNode) => t.type === 'topic')
      return String((topicTag ?? tags[0]).name ?? '')
    }
    const desc = String(detail.desc ?? '')
    const hashMatch = desc.match(/#([^#\[]+)/)
    if (hashMatch?.[1]?.trim()) return hashMatch[1].trim()
    const title = String(detail.title ?? detail.displayTitle ?? '')
    return title.slice(0, 20) || null
  }, noteId)
  if (!tagKeyword) {
    const domKeyword = await page.evaluate(() => {
      const tagEls = document.querySelectorAll('.note-tag, [class*="tag"] a, a[href*="search_result"]')
      for (const el of tagEls) {
        const text = el.textContent?.replace(/#/g, '').trim()
        if (text) return text
      }
      const titleEl = document.querySelector('.note-title, [class*="title"]')
      const titleText = titleEl?.textContent?.trim()
      return titleText?.slice(0, 20) || null
    })
    if (!domKeyword) return { notes: [], count: 0 }
    const searchApiPromise2 = page.waitForResponse(
      (resp) => resp.url().includes('/api/sns/web/v1/search/notes') && resp.status() === 200,
      { timeout: 15000 },
    ).catch(() => null)
    await page.goto(
      `${BASE}/search_result?keyword=${encodeURIComponent(domKeyword)}&source=web_search_result_notes`,
      { waitUntil: 'domcontentloaded', timeout: 30000 },
    )
    await page.waitForTimeout(4000)
    const ssrFallback = await page.evaluate((excludeId: string) => {
      const state = (window as XhsWindow).__INITIAL_STATE__
      if (!state?.search) return null
      const feedsRef = state.search.feeds
      const feeds: SsrNode[] = feedsRef?._rawValue ?? feedsRef ?? []
      if (!Array.isArray(feeds) || feeds.length === 0) return null
      const notes = feeds
        .filter((f: SsrNode) => f.modelType === 'note' && f.noteCard && String(f.id) !== excludeId)
        .slice(0, 10)
        .map((f: SsrNode) => {
          const card = f.noteCard
          return {
            noteId: f.id, xsecToken: f.xsecToken, type: card.type, displayTitle: card.displayTitle,
            user: card.user ? { userId: card.user.userId, nickname: card.user.nickname, avatar: card.user.avatar } : null,
            likedCount: card.interactInfo?.likedCount ?? null,
            cover: card.cover ? { url: card.cover.urlDefault, width: card.cover.width, height: card.cover.height } : null,
          }
        })
      return notes.length > 0 ? { notes, count: notes.length } : null
    }, noteId)
    if (ssrFallback) return ssrFallback
    const searchResp2 = await searchApiPromise2
    if (searchResp2) {
      try {
        const json = (await searchResp2.json()) as Record<string, unknown>
        const data = asRecord(json.data)
        const items = data.items as Array<Record<string, unknown>> | undefined
        if (Array.isArray(items) && items.length > 0) {
          const notes = items
            .filter((item: SsrNode) => item.model_type === 'note' && String(item.id) !== noteId)
            .slice(0, 10)
            .map((item: SsrNode) => {
              const card = item.note_card
              return {
                noteId: item.id, xsecToken: item.xsec_token, type: card?.type, displayTitle: card?.display_title ?? '',
                user: card?.user ? { userId: card.user.user_id, nickname: card.user.nickname, avatar: card.user.avatar } : null,
                likedCount: card?.interact_info?.liked_count ?? null,
                cover: card?.cover ? { url: card.cover.url_default ?? card.cover.url, width: card.cover.width, height: card.cover.height } : null,
              }
            })
          return { notes, count: notes.length }
        }
      } catch { /* fall through */ }
    }
    return { notes: [], count: 0 }
  }
  const searchApiPromise = page.waitForResponse(
    (resp) => resp.url().includes('/api/sns/web/v1/search/notes') && resp.status() === 200,
    { timeout: 15000 },
  ).catch(() => null)
  await page.goto(
    `${BASE}/search_result?keyword=${encodeURIComponent(tagKeyword)}&source=web_search_result_notes`,
    { waitUntil: 'domcontentloaded', timeout: 30000 },
  )
  await page.waitForTimeout(4000)
  const ssrResult = await page.evaluate((excludeId: string) => {
    const state = (window as XhsWindow).__INITIAL_STATE__
    if (!state?.search) return null
    const feedsRef = state.search.feeds
    const feeds: SsrNode[] = feedsRef?._rawValue ?? feedsRef ?? []
    if (!Array.isArray(feeds) || feeds.length === 0) return null
    const notes = feeds
      .filter((f: SsrNode) => f.modelType === 'note' && f.noteCard && String(f.id) !== excludeId)
      .slice(0, 10)
      .map((f: SsrNode) => {
        const card = f.noteCard
        return {
          noteId: f.id, xsecToken: f.xsecToken, type: card.type, displayTitle: card.displayTitle,
          user: card.user ? { userId: card.user.userId, nickname: card.user.nickname, avatar: card.user.avatar } : null,
          likedCount: card.interactInfo?.likedCount ?? null,
          cover: card.cover ? { url: card.cover.urlDefault, width: card.cover.width, height: card.cover.height } : null,
        }
      })
    return notes.length > 0 ? { notes, count: notes.length } : null
  }, noteId)
  if (ssrResult) return ssrResult
  const searchResp = await searchApiPromise
  if (searchResp) {
    try {
      const json = (await searchResp.json()) as Record<string, unknown>
      const data = asRecord(json.data)
      const items = data.items as Array<Record<string, unknown>> | undefined
      if (Array.isArray(items) && items.length > 0) {
        const notes = items
          .filter((item: SsrNode) => item.model_type === 'note' && String(item.id) !== noteId)
          .slice(0, 10)
          .map((item: SsrNode) => {
            const card = item.note_card
            return {
              noteId: item.id, xsecToken: item.xsec_token, type: card?.type, displayTitle: card?.display_title ?? '',
              user: card?.user ? { userId: card.user.user_id, nickname: card.user.nickname, avatar: card.user.avatar } : null,
              likedCount: card?.interact_info?.liked_count ?? null,
              cover: card?.cover ? { url: card.cover.url_default ?? card.cover.url, width: card.cover.width, height: card.cover.height } : null,
            }
          })
        return { notes, count: notes.length }
      }
    } catch { /* fall through */ }
  }
  return { notes: [], count: 0 }
}

async function followUser(page: Page, params: Record<string, unknown>, errors: Errors): Promise<unknown> {
  const userId = String(params.userId ?? params.user_id ?? '')
  if (!userId) throw errors.missingParam('userId')
  await page.goto(`${BASE}/user/profile/${userId}`, { waitUntil: 'domcontentloaded', timeout: 30000 })
  if (page.url().includes('login')) throw errors.needsLogin()
  if (page.url().includes('captcha')) throw errors.needsLogin()
  await page.waitForTimeout(3000)
  const wasFollowing = await page.evaluate(() => {
    const state = (window as XhsWindow).__INITIAL_STATE__
    const pageDataRef = state?.user?.userPageData
    const pageData: Record<string, SsrNode> = pageDataRef?._rawValue ?? pageDataRef ?? {}
    const basicInfo = pageData.basicInfo?._rawValue ?? pageData.basicInfo ?? {}
    return basicInfo.isFollowed ?? false
  })
  if (wasFollowing) return { userId, followed: true, action: 'already_following' }
  const followPromise = page.waitForResponse(
    (resp) => resp.url().includes('/api/sns/web/v1/user/follow') && resp.status() === 200,
    { timeout: 10000 },
  ).catch(() => null)
  await page.click('.user-actions button:has-text("关注"), .info-part button:has-text("关注"), [class*="follow"]:not([class*="fans"])', { timeout: 5000 })
  const followResp = await followPromise
  const success = !!followResp
  return { userId, followed: success, action: success ? 'followed' : 'failed' }
}

async function commentNote(page: Page, params: Record<string, unknown>, errors: Errors): Promise<unknown> {
  const noteId = String(params.noteId ?? params.note_id ?? '')
  if (!noteId) throw errors.missingParam('noteId')
  const content = String(params.content ?? '')
  if (!content) throw errors.missingParam('content')
  const xsecToken = String(params.xsecToken ?? params.xsec_token ?? '')
  await navigateToNote(page, { noteId, xsecToken }, errors)
  const commentPromise = page.waitForResponse(
    (resp) => resp.url().includes('/api/sns/web/v1/comment/post') && resp.status() === 200,
    { timeout: 10000 },
  ).catch(() => null)
  const commentInput = page.locator('#content-textarea, [class*="comment"] textarea, [placeholder*="评论"]')
  await commentInput.click({ timeout: 5000 })
  await commentInput.fill(content)
  await page.waitForTimeout(500)
  await page.click('[class*="comment"] button:has-text("发送"), [class*="submit"]:has-text("发送"), button.submit', { timeout: 5000 })
  const commentResp = await commentPromise
  if (commentResp) {
    try {
      const json = (await commentResp.json()) as Record<string, unknown>
      const data = asRecord(json.data)
      return { noteId, commentId: data.comment?.id ?? data.id ?? null, content, action: 'commented' }
    } catch { /* fall through */ }
  }
  return { noteId, commentId: null, content, action: 'failed' }
}

/* ---------- adapter export ---------- */

type OpHandler = (page: Page, params: Record<string, unknown>, errors: Errors) => Promise<unknown>

const OPERATIONS: Record<string, OpHandler> = {
  searchNotes, getNoteDetail, getUserProfile, getUserNotes, getExploreFeed,
  likeNote, bookmarkNote, getHotSearch, getNoteComments, getUserCollections,
  getUserLiked, getRelatedNotes, followUser, commentNote,
}

const adapter: CustomRunner = {
  name: 'xiaohongshu-web',
  description: 'Xiaohongshu (小红书) — search, detail, profile, notes, explore, comments, collections, likes, related notes, follow, like, bookmark, comment via Vue SSR + API interception',

  async run(ctx) {
    const { page, operation, params, helpers } = ctx
    const { errors } = helpers as { errors: Errors }
    try {
      const handler = OPERATIONS[operation]
      if (!handler) throw errors.unknownOp(operation)
      return await handler(page as Page, { ...params }, errors)
    } catch (error) {
      throw errors.wrap(error)
    }
  },
}

export default adapter
